upload-doc = false
sign-commit = true
no-dev-version = true
pre-release-replacements = [ 
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"}, 
    {file="CITATION.cff", search="version: [0-9.]+", replace="version: {{version}}"}, 
    {file="CITATION.cff", search="date-released: [0-9\\-]+", replace="date-released: {{date}}"}, 
